Determine specific versions of Mac OS
cegredev/josi pull request #2
Opened 2021-04-23 03:31 UTC by RohanNagar

Hi! Really awesome library, I love how lightweight it is.

I wanted to contribute to adding specific versions of Mac OS.

From [this doc](https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html), I found the `os.version` property. For Mac, this returns a string in the form `10.x.x`. I matched that up to the version names from [here](https://en.wikipedia.org/wiki/MacOS_version_history#Releases).

Please let me know what you think!

2021-04-23 11:47 UTC, cegredev requested changes
This is awesome, wow! Thanks a lot!

I have a few things to address before I merge:
 - It'd be nice if we could keep the style of `WIN_UNKNOWN` for the other families as well, i.e. rename `OS.MAC` to something like `MAC_UNKNOWN` or `MAC_OS_UNKNOWN`
 - Are you sure that the version number for Big Sur is 10.16 instead of 11 like shown in the Wikipedia article (l. 176, OS.java)?
 - How can you confirm that the version actually comes in this format? If you just have one Mac machine and it's formatted like that, it's probably fair to assume the rest is as well, but it's important to me that you aren't just guessing. ;)

...also, you can edit pull requests in the way I described, right? Kinda new to this and don't know if what I'm asking you is possible o.O

2021-04-23 12:08 UTC, cegredev commented
![](https://github.trello.services/images/mini-trello-icon.png) [More Mac versions](https://trello.com/c/yv90DyLF/1-more-mac-versions)

2021-04-23 15:14 UTC, RohanNagar commented
Hey @cegredev, thanks for the feedback. I just pushed an update to rename `OS.MAC` to `OS.MAC_UNKNOWN`.

As for your other questions:

> Are you sure that the version number for Big Sur is 10.16 instead of 11 like shown in the Wikipedia article (l. 176, OS.java)?

I am running Big Sur (version 11.2.3) locally and I get 10.16 for `os.version`, as you can see:

<img width="466" alt="Screen Shot 2021-04-23 at 8 13 37 AM" src="https://user-images.githubusercontent.com/5522930/115892232-d16b5580-a40b-11eb-99ea-f16904e4643d.png">

> How can you confirm that the versions actually come in this format? If you just have one Mac machine and it's formatted like that, it's probably fair to assume the rest is as well, but it's important to me that you aren't just guessing. ;)

Yes, I have two Mac machines, one on Big Sur and one on Catalina. Big Sur returns 10.16 for the version, and Catalina returns 10.15.7.

Also, I found [this old stack overflow](https://stackoverflow.com/questions/12466803/java-how-can-i-determine-the-running-mac-os-x-version-with-code) post where `os.version` returned 10.7.4 on Lion.

Hope that helps!

2021-04-23 15:28 UTC, cegredev approved these changes
Perfect! Thanks a lot for your help! I'll be releasing a new release soon.

2021-04-23 15:28 UTC, merged

2021-04-29 16:50 UTC, dbwiddis commented
If you look at the [JDK source code](https://github.com/openjdk/jdk/blob/66757750a2adf0739d0f5bf98a3f50a123b7adcf/src/java.base/macosx/native/libjava/java_props_macosx.c#L264), it looks like they also will/do report 11.x versions.   I'm sure for some time they also report 10.16 but you should handle both.

2021-04-29 20:21 UTC, RohanNagar commented
@dbwiddis I opened #4 to address this.