Add isAtLeast(OS) method
cegredev/josi pull request #5
Opened 2021-04-30 02:41 UTC by dbwiddis

Fixes #3 

Makes the assumption the "Unknown" versions are newer, which might not be true but is more likely to be true than not.

Used your same formatting with tabs, which are evil. ;)

2021-04-30 15:30 UTC, dbwiddis commented on src/main/java/io/github/cegredev/josi/OS.java
> +		enforceFamily(Family.MAC, Family.WINDOWS);
I realized later perhaps we can allow other OS's to equal each other if the family matches so this should probably be changed to `enforceNotFamily(Family.UNKNOWN)`

2021-04-30 15:31 UTC, dbwiddis commented on src/test/java/io/github/cegredev/josi/OSCheckTests.java
> +		assertThrows(UnsupportedOSException.class, () -> OS.UBUNTU.isAtLeast(OS.UBUNTU),
This should maybe be changed to be "true".

2021-04-30 15:33 UTC, cegredev requested changes
This is a great idea, thanks a lot!

One thing I'd like to change is the fact that you have those `enforce` calls inside `isAtLeast`. I can understand why one would want to throw an exception in those cases but in my opinion that is overkill in this scenario and just returning `false` would be enough. I can see this method being used instead of `OS.isFamily` and we wouldn't want that throwing an exception if the result was false.

Also, based on the other helper methods the user doesn't expect one starting with "is" to throw an exception. That's what "enforce" is for. For this reason I'd actually like to keep the code you wrote, but move it to a separate function `public void enforceAtLeast(OS operatingSystem)` and have it throw an exception if the result of `compareTo` is smaller than 0.

2021-04-30 15:39 UTC, cegredev commented
> So two methods; the `isAtLeast()` just returning false on family mismatch (or unknown family) or incorrect version alignment, and `enforceAtLeast()` doing similar but with exceptions (and probably just calling `isAtLeast()` internally)?

Yes, exactly! :)

2021-05-02 16:24 UTC, cegredev commented
About this: I'm not sure if you missed my last comment...

> Yes, but that is only the case if you just consider the family of the operating system. Take Solaris for example. As of right now, it is the only member of the OTHER family (besides UNKNOWN of course). If I were to say OS.SOLARIS.isAtLeast(OS.SOLARIS) that would return false, even though that's clearly wrong.
> 
> I agree that OS.UNKNOWN and OS.UNKNOWN should return false, but not OS.Family.OTHER and OS.Family.OTHER.

...but that's the reason I haven't merged this yet. I'd have no problem merging and then implementing this little fix myself, but before I do that I wanted to make sure I don't go over your head, in case you do actually want to do this yourself or disagree.

2021-05-02 19:30 UTC, dbwiddis commented
I think I got confused by UNKNOWN (OS) vs. OTHER (Family).   Really the correct solution is to put SOLARIS in a UNIX family along with AIX (which currently matches into LINUX).  Although you can change that conditional to just an UNKNOWN OS.  I'm fine if you want to tweak the logic after you merge (or even push to the PR fork before you merge... if you haven't learned how to do that as a maintainer, you should! )

2021-05-02 19:49 UTC, cegredev commented
> put SOLARIS in a UNIX family along with AIX

Yep, I'll implement that soon.

> push to the PR fork before you merge... if you haven't learned how to do that as a maintainer, you should!

Just did that. I really am trying my best to do a good job of this, even though I'm new to all of it, believe me. I look forward to learning a lot more as this project progresses, haha.

2021-05-02 19:49 UTC, merged

2021-05-02 19:53 UTC, dbwiddis commented
> I look forward to learning a lot more as this project progresses, haha.

It's really one of the best places out there to self-learn software engineering!  Try getting hired as a senior software engineer based primarily on 7 years of maintaining an open source project. ;)

2021-05-02 19:56 UTC, cegredev commented
Haha, sounds like a good plan, see you in 7 years then ;)